### PR TITLE
Project setup request

### PR DESCRIPTION
**Pull request by Mikearaya**
On this pull request, we have created the project structure and  created an executable `main.rb` file.

**Kindly requesting your review so we can proceed to the second milestone of the project**

**Thank you** :bowing_man:

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
The project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Great work :+1: 
Just a one more change required:
* [x] Stickler is not checking this Pull Request, make sure you set it up correctly. It can be turned off on `https://stickler-ci.com/`, make sure you turned stickler on for this repository.

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by Mikearaya** [comment]
:disappointed:

**Comment by Anna-Myzukina** [comment]
## Hi team ! Very nice start! :wave: 

# [APPROVED]  :+1:

### Go and merge to develop.
`Goodluck in your next milestones Happy coding ` <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Pull request merged**
